import mlflow
import mlflow.sklearn
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
import warnings

warnings.filterwarnings("ignore")

EXPERIMENT_NAME = "Churn_Prediction"

# Search space specifies the bounds Hyperopt will be sampling from for each variable.
# quniform results in integer-valued samples (quantized to the specified step size),
# while uniform returns real-valued samples within the specified range.
SEARCH_SPACE = {
    "n_estimators":  hp.quniform("n_estimators",  50, 300, 25),  # Number of trees
    "learning_rate": hp.uniform("learning_rate",  0.01, 0.3),    # Contribution of each tree
    "max_depth":     hp.quniform("max_depth",      2, 6, 1),      # Depth limit for each tree
    "subsample":     hp.uniform("subsample",       0.6, 1.0),     # Fraction of samples for each tree
    "max_features":  hp.uniform("max_features",    0.5, 1.0),     # fraction of features per split
}


def tune_model(X_train, X_test, y_train, y_test, max_evals=50):
    """
    Runs Bayesian hyperparameter optimization using the TPE algorithm from Hyperopt.

    How it works:
        - Each trial trains a Gradient Boosting model with a different parameter set
        - 3-fold cross-validation on the training set gives a reliable AUC estimate
        - Hyperopt uses past trial results to make smarter guesses for the next trial
        - Every trial is logged as a nested MLflow run for full traceability
        - After all trials, the best parameters are used to retrain on the full set

    Args:
        max_evals: number of parameter combinations to evaluate (default 50)

    Returns:
        best_model, best_params, tuning_run_id
    """

    print("-" * 50)
    print("Phase 3: Hyperparameter Tuning")
    print("-" * 50)
    print(f"Running {max_evals} trials with Hyperopt TPE\n")

    mlflow.set_tracking_uri("./mlruns")
    mlflow.set_experiment(EXPERIMENT_NAME)

    trial_count = [0]   # using a list so that the inner function can alter it
    best_score  = [0.0]

    def objective(params):
        """
        Objective function called by Hyperopt for each trial.
        Returns the loss (1 - AUC) so Hyperopt can minimize it.
        """
        trial_count[0] += 1

        # Convert floating-point numbers generated by Hyperopt to the proper data type
        clean_params = {
            "n_estimators":  int(params["n_estimators"]),
            "learning_rate": round(params["learning_rate"], 4),
            "max_depth":     int(params["max_depth"]),
            "subsample":     round(params["subsample"], 4),
            "max_features":  round(params["max_features"], 4),
            "random_state":  42
        }

        # Log this particular trial as a nested run under the tuning experiment
        with mlflow.start_run(
            run_name=f"Trial_{trial_count[0]:03d}", nested=True
        ):
            mlflow.set_tag("run_type", "hyperparameter_tuning")
            mlflow.log_params(clean_params)

            model = GradientBoostingClassifier(**clean_params)

            # A 3-fold cross-validation provides a better estimate of AUC than a single train/test split
            cv_scores = cross_val_score(
                model, X_train, y_train,
                cv=3, scoring="roc_auc", n_jobs=-1
            )
            mean_auc = cv_scores.mean()
            std_auc  = cv_scores.std()

            # Run the model performance evaluation on the separate test set for comparison
            model.fit(X_train, y_train)
            test_auc = roc_auc_score(
                y_test, model.predict_proba(X_test)[:, 1]
            )

            mlflow.log_metrics({
                "cv_auc_mean": round(mean_auc, 4),
                "cv_auc_std":  round(std_auc, 4),
                "test_auc":    round(test_auc, 4)
            })

            # Mark this particular trial as the best one in the user interface
            if mean_auc > best_score[0]:
                best_score[0] = mean_auc
                mlflow.set_tag("best_trial", "true")

        # Display the status periodically
        if trial_count[0] % 10 == 0 or trial_count[0] == 1:
            print(f"  Trial {trial_count[0]:3d}/{max_evals} "
                  f"| AUC: {mean_auc:.4f} "
                  f"| Best: {best_score[0]:.4f}")

        # As Hyperopt attempts to minimize the output, we return 1 - AUC
        return {"loss": 1 - mean_auc, "status": STATUS_OK}

    trials = Trials()  # stores information about all trials for review

    # Run the complete tuning process within a top-level MLflow run
    with mlflow.start_run(run_name="Hyperopt_Tuning_Session"):
        mlflow.set_tag("run_type", "tuning_session")
        mlflow.log_params({
            "max_evals":  max_evals,
            "algorithm":  "TPE",
            "base_model": "GradientBoostingClassifier"
        })

        best_raw = fmin(
            fn=objective,
            space=SEARCH_SPACE,
            algo=tpe.suggest,   # Tree of Parzen Estimators (TPE)—smarter than simple random search
            max_evals=max_evals,
            trials=trials,
            verbose=False
        )

        # Clean up the Hyperopt result format to create useful parameter objects
        best_params = {
            "n_estimators":  int(best_raw["n_estimators"]),
            "learning_rate": round(best_raw["learning_rate"], 4),
            "max_depth":     int(best_raw["max_depth"]),
            "subsample":     round(best_raw["subsample"], 4),
            "max_features":  round(best_raw["max_features"], 4),
            "random_state":  42
        }

        # Retrain using the entire data set and the optimized hyperparameters
        best_model = GradientBoostingClassifier(**best_params)
        best_model.fit(X_train, y_train)

        final_auc = roc_auc_score(
            y_test, best_model.predict_proba(X_test)[:, 1]
        )

        # Store the best parameters and model in the parent MLflow run
        mlflow.log_params({f"best_{k}": v for k, v in best_params.items()})
        mlflow.log_metric("best_test_auc", round(final_auc, 4))
        mlflow.sklearn.log_model(
            sk_model=best_model,
            artifact_path="best_tuned_model",
            input_example=X_train.iloc[:3]
        )

        tuning_run_id = mlflow.active_run().info.run_id

    print(f"\nBest parameters found:")
    for k, v in best_params.items():
        if k != "random_state":
            print(f"  {k:<20}: {v}")
    print(f"\nBest Test AUC-ROC: {final_auc:.4f}\n")

    return best_model, best_params, tuning_run_id


if __name__ == "__main__":
    import sys
    sys.path.insert(0, ".")
    from src.data_prep import load_and_prepare_data
    X_train, X_test, y_train, y_test, feat = load_and_prepare_data()
    tune_model(X_train, X_test, y_train, y_test, max_evals=20)
